plugins {
    id 'org.openjfx.javafxplugin' version "$javafxPluginVersion"
    id 'jpro-gradle-plugin'
}

version = "$projectVersion"
group = 'one.jpro'

java {
    sourceCompatibility = JavaVersion.VERSION_22
    targetCompatibility = JavaVersion.VERSION_22
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'one.jpro:jpro-webapi:$jproVersion'
    implementation "fr.brouillard.oss:cssfx:$cssfxVersion"
}

javafx {
    version = "$javafxVersion"
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    // Define the main class for the application.
    mainClass = 'one.jpro.hellojpro.HelloJPro'
}

jpro {
    // jpro server port
    port = 8080
}
