name: CI build

on: [push]

jobs:
  builds:
    name: ${{ matrix.os }} with Java ${{ matrix.jdk }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [17, 21]
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
      max-parallel: 4
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
      - name: Compile
        run: |
          ./gradlew clean jar