name: Release build

on:
  push:
    branches:
      - release
#    tags:
#        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Create JPro distribution
        run: |
          ./gradlew clean jproRelease
      - name: Make release directory
        run: |
          mkdir release
          ls build/distributions/
          cp -r build/distributions/*-jpro.zip release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          name: Release
          path: release
          asset_name: hellojpro-gradle-jpro.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is a JPro release build."